# Generated by Django 4.2.1 on 2024-08-25 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0002_remove_doctor_name_remove_doctor_slug'),
        ('paitent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.TextField()),
                ('type', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=15)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('cancelled', 'cancelled'), ('completed', 'completed')], default='pending', max_length=15)),
                ('cancel', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
                ('paitent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paitent.paitent')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.availabletime')),
            ],
        ),
    ]
