# Generated by Django 4.2.1 on 2024-08-28 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_appointment_doctor_review_alter_appointment_paitent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='cancel',
        ),
    ]
