# Generated by Django 4.2.1 on 2024-08-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_remove_doctor_name_remove_doctor_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='meet_link',
            field=models.TextField(default=None, null=True),
        ),
    ]
