# Generated by Django 4.2.1 on 2024-08-27 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paitent', '0003_alter_paitent_age_alter_paitent_user'),
        ('doctor', '0003_doctor_meet_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='meet_link',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(choices=[('⭐', '⭐'), ('⭐⭐', '⭐⭐'), ('⭐⭐⭐', '⭐⭐⭐'), ('⭐⭐⭐⭐', '⭐⭐⭐⭐'), ('⭐⭐⭐⭐⭐', '⭐⭐⭐⭐⭐')], max_length=5)),
                ('review', models.TextField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='doctor.doctor')),
                ('paitent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='paitent.paitent')),
            ],
        ),
    ]
